from surrogates.gcn_blr.gcn_blr import GCN_BLR
from surrogates.weisfeiler_lehman.predictors.gp_predictor import GPWL
from surrogates.weisfeiler_lehman.predictors.neural_ensemble_predictor import NeuralEnsemble
from surrogates.weisfeiler_lehman.predictors.bayes_linregress_predictor import BayesianLinearRegression
from surrogates.gnn.gcn import GCNPredictor